// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alphabet: typeof import('./src/components/Alphabet.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputGroup: typeof import('./src/components/InputGroup.vue')['default']
    Location: typeof import('./src/components/Location.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Restaurants: typeof import('./src/components/Restaurants.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
